Public Module StringResourceHolder

    Public MustInherit Class StringResourceBase
        Public nl As String = Environment.NewLine
        Public FileHead As String = "; 由 OBJ->CSV 转换工具 生成" & nl & "; 编程：Zbx1425 (百度贴吧 zbx14251, Email: zbx1425@126.com)" & nl & "; Generated by Obj2Csv Conventor" & nl & "; By zbx1425 (zbx1422 at BVE Worldwide, Email: zbx1425@126.com)"

        Public Copyright As String

        Public ReadStarted As String
        Public ReadingGroup As String
        Public ReadFinished As String
        Public MeshConverting As String
        Public MeshConverted As String
        Public MeshExported As String
        Public ExportFinished As String
        Public TotalTime As String
        Public ErrorReport As String

        Public ErrorInputNotFound As String
        Public ErrorWrongInstruction As String
        Public ErrorMissingVertex As String
        Public ErrorCurveVertex As String
        Public ErrorMatLibNotFound As String
        Public ErrorUnknownCommand As String
        Public ErrorMatLibNotLoaded As String

        Public OpenFileTitle As String
        Public OpenFileFilter As String
        Public WarningFaceNotConverted As String
    End Class

    Public Class Chinese
        Inherits StringResourceBase

        Public Sub New()
            Copyright = "OBJ->CSV 转换工具" & nl & "编程：Zbx1425 (百度贴吧 zbx14251)" & nl & "Email: zbx1425@126.com" & nl & "版本 {0}" & nl & "--------------------------------------"

            ReadStarted = "正在读入Obj……"
            ReadingGroup = "正在读入分组 {0} ……"
            ReadFinished = "Obj读入完成，共 {0} 个面，开始转换。"
            MeshConverting = "已转换 {0} / {1} 个面。"
            MeshConverted = "材质 {0} 对应面顶点转换完成。"
            MeshExported = "材质 {0} 对应面导出完成，已导出 {1} 个面。"
            ExportFinished = nl & "** 导出完成，谢谢。 **" & nl & nl & "转换过程中载入了{0}个材质。" & nl & "导出了 {1} 个面， {2} 个面转换失败。"
            TotalTime = "共用时 {0} 秒。"
            ErrorReport = "发生错误： {0}" & nl & "{1}" & nl & nl & "** 转换失败。 **"

            ErrorInputNotFound = "未找到输入文件，请检查拼写错误。"
            ErrorWrongInstruction = "指令格式不正确。"
            ErrorMissingVertex = "面定义非法，请检查空格。"
            ErrorCurveVertex = "本转换器只支持简单面。请在导出时选择""不使用曲面"""
            ErrorMatLibNotFound = "没有找到MTL文件。请重新导出。"
            ErrorUnknownCommand = "不支持或非法的指令： {0}"
            ErrorMatLibNotLoaded = "与材质对应的MTL未载入。请在导出时选择""导出材质库""。"

            OpenFileTitle = "打开OBJ输入"
            OpenFileFilter = "Wavefront OBJ|*.obj"
            WarningFaceNotConverted = "没有绑定材质库(MTL)的面没有被转换。请检查是否有物体没有绑定材质，或导出的材质库是否齐全。"
        End Sub
    End Class

    Public Class English
        Inherits StringResourceBase

        Public Sub New()
            Copyright = "OBJ2CSV Convertor" & nl & "Programmed by zbx1425 (on BVE Worldwide)" & nl & "Email: zbx1425@126.com" & nl & "Ver {0}" & nl & "--------------------------------------"

            ReadStarted = "Parsing Obj……"
            ReadingGroup = "Group {0} detected……"
            ReadFinished = "Obj parsed，{0} face(s) in total，conversion started."
            MeshConverting = "{0} / {1} face(s) converted."
            MeshConverted = "The face(s) which have material {0} are converted."
            MeshExported = "The face(s) which have material {0} are exported. {1} face(s) are exported till now."
            ExportFinished = nl & "** Export finished, Thank you. **" & nl & nl & "{0} material(s) loaded, " & nl & "{1} face(s) succeed, {2} failed."
            TotalTime = "Used time: {0} seconds."
            ErrorReport = "Error occured: {0}" & nl & "{1}" & nl & nl & "** Convert failed. **"

            ErrorInputNotFound = "Input not found, please check for spell errors."
            ErrorWrongInstruction = "Incorrect Obj instruction."
            ErrorMissingVertex = "Invaild face defination, please check for spaces in the Obj file."
            ErrorCurveVertex = "This convertor does not support curves. Please use simple faces only."
            ErrorMatLibNotFound = "Material Lib not found. Make sure you have exported or copied it correctly."
            ErrorUnknownCommand = "Not adapted or illegal instruction: {0}"
            ErrorMatLibNotLoaded = "Material Lib not loaded. Make sure you have exported it."

            OpenFileTitle = "Open OBJ For Input"
            OpenFileFilter = "Wavefront OBJ|*.obj"
            WarningFaceNotConverted = "The face(s) without a material are not converted. Please check if you forgot to apply the material, or did not have the Material Lib exported."
        End Sub
    End Class

    Public StringResource As StringResourceBase

    Public Sub InitalizeStringResource()
        Dim language As Globalization.CultureInfo = System.Globalization.CultureInfo.InstalledUICulture
        Select Case language.Name
            Case "zh-CN", "zh-TW"
                StringResource = New Chinese
            Case Else
                StringResource = New English
        End Select
    End Sub

End Module
