Public Module StringResource
    Public nl As String = Environment.NewLine

    Public Copyright As String = "OBJ->CSV 转换工具" & nl & "编程：Zbx1425 (百度贴吧 zbx14251)" & nl & "版本 {0}" & nl & "--------------------------------------"
    Public FileHead As String = "; 由 OBJ->CSV 转换工具 生成" & nl & "; 编程：Zbx1425 (百度贴吧 zbx14251, Email: zbx1425@126.com)" & nl & "; Generated by Obj2Csv Conventor" & nl & "; By zbx1425 (email: zbx1425@126.com)"

    Public ReadStarted As String = "正在读入Obj……"
    Public ReadingGroup As String = "正在读入分组 {0} ……"
    Public ReadFinished As String = "Obj读入完成，共 {0} 个面，开始转换。"
    Public MeshConverting As String = "已转换 {0} / {1} 个面。"
    Public MeshConverted As String = "材质 {0} 对应面顶点转换完成。"
    Public ConvertFinished As String = "顶点指令转换完成。开始导出。"
    Public MeshExported As String = "材质 {0} 对应面导出完成，已导出 {1} 个面。"
    Public ExportFinished As String = nl & "** 导出完成，谢谢。 **" & nl & nl & "转换过程中载入了{0}个材质。" & nl & "导出了 {1} 个面， {2} 个面转换失败。"
    Public TotalTime As String = "共用时 {0} 秒。"
    Public ErrorReport As String = "发生错误： {0}" & nl & "{1}" & nl & nl & "** 转换失败。 **"

    Public ErrorInputNotFound As String = "未找到输入文件，请检查拼写错误。"
    Public ErrorWrongInstruction As String = "指令格式不正确。"
    Public ErrorMissingVertex As String = "面定义非法，请检查空格。"
    Public ErrorCurveVertex As String = "本转换器只支持简单面。请在导出时选择""不使用曲面"""
    Public ErrorMatLibNotFound As String = "没有找到MTL文件。请重新导出。"
    Public ErrorUnknownCommand As String = "不支持或非法的指令： {0}"
    Public ErrorMatLibNotLoaded As String = "与材质对应的MTL未载入。请在导出时选择""导出材质库""。"

    Public OpenFileTitle As String = "打开OBJ输入"
    Public OpenFileFilter As String = "Wavefront OBJ|*.obj"
    Public WarningFaceNotConverted As String = "没有绑定材质库(MTL)的面没有被转换。请检查是否有物体没有绑定材质，或导出的材质库是否齐全。"

End Module
